services:
  - type: web
    name: sae301
    env: php
    rootDir: erddap-api
    region: frankfurt
    plan: free
    buildCommand: composer install --optimize-autoloader --no-dev
    startCommand: php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=8080
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: true
      - key: APP_ENV
        value: production
      - key: APP_NAME
        value: Sae301
      - key: DB_CONNECTION
        value: mysql
      - key: DB_PORT
        value: 4000
      - key: DB_SSL_MODE
        value: required
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false